"""Smoke test for Arnold-Hess official WAVES integration.

The test is intentionally tiny and CPU-only. It verifies that Arnold-Hess can be
embedded, decoded into the official WAVES JSON format, and evaluated with
lightweight WAVES image metrics. It creates a WAVES-style attacked folder by
copying the watermarked image; attack generation itself is intentionally not
implemented here, because attacks should come from official WAVES.
"""
from __future__ import annotations

import importlib
import json
import os
from pathlib import Path

import cv2
import numpy as np


REPO = Path(__file__).resolve().parents[1]


def _make_synthetic_inputs(root: Path):
    input_dir = root / "input_images"
    input_dir.mkdir(parents=True, exist_ok=True)

    h = w = 128
    yy, xx = np.mgrid[0:h, 0:w]
    b = (xx % 256).astype(np.uint8)
    g = ((yy * 2) % 256).astype(np.uint8)
    r = (((xx + yy) // 2) % 256).astype(np.uint8)
    img = np.dstack([b, g, r])
    host_path = input_dir / "host_0.png"
    cv2.imwrite(str(host_path), img)

    wm = np.zeros((16, 16), dtype=np.uint8)
    wm[::2, :] = 255
    wm[:, ::7] = 255
    wm[5:11, 5:11] = 255 - wm[5:11, 5:11]
    wm_path = root / "wm.png"
    cv2.imwrite(str(wm_path), wm)
    return input_dir, host_path, wm_path


def test_arnold_hess_official_pipeline(tmp_path, monkeypatch):
    data_dir = tmp_path / "data"
    result_dir = tmp_path / "results"
    cache_dir = tmp_path / "cache"
    for d in [data_dir, result_dir, cache_dir]:
        d.mkdir(parents=True, exist_ok=True)

    input_dir, host_path, wm_path = _make_synthetic_inputs(tmp_path)

    monkeypatch.setenv("DATA_DIR", str(data_dir))
    monkeypatch.setenv("RESULT_DIR", str(result_dir))
    monkeypatch.setenv("CACHE_DIR", str(cache_dir))
    monkeypatch.setenv("MODEL_DIR", str(REPO / "decoders"))
    monkeypatch.setenv("ARNOLD_HESS_WM_PATH", str(wm_path))
    monkeypatch.setenv("WAVES_LIMIT", "1")
    monkeypatch.setenv("WAVES_SUBSET_LIMIT", "1")
    monkeypatch.setenv("ARNOLD_HESS_MAX_REPEAT_FACTOR", "1")
    monkeypatch.setenv("ARNOLD_HESS_FAST_EMBED", "1")
    monkeypatch.setenv("ARNOLD_HESS_HOST_SIZE", "128")
    monkeypatch.setenv("ARNOLD_HESS_WM_SIZE", "16")

    # Import after env is set so constants use the test sizes.
    from watermarks import arnold_hess as core
    from watermarks.arnold_hess_adapter import embed_image
    from dev import load_json, decode_array_from_string
    import scripts.decode as decode_script
    import scripts.metric as metric_script

    importlib.reload(core)
    importlib.reload(decode_script)
    importlib.reload(metric_script)

    real_dir = data_dir / "main" / "custom" / "real"
    wm_dir = data_dir / "main" / "custom" / "arnold_hess"
    side_dir = data_dir / "side_info" / "custom" / "arnold_hess"
    attacked_wm_dir = data_dir / "attacked" / "custom" / "distortion_single_jpeg-0.5-arnold_hess"
    for d in [real_dir, wm_dir, side_dir, attacked_wm_dir]:
        d.mkdir(parents=True, exist_ok=True)

    real_out = real_dir / "0.png"
    wm_out = wm_dir / "0.png"
    side_out = side_dir / "0.npz"

    host_img = core.load_color_image_24bit_safe(str(host_path), size=128)
    cv2.imwrite(str(real_out), host_img)
    embed_image(str(host_path), str(wm_path), str(wm_out), str(side_out))

    assert real_out.exists()
    assert wm_out.exists()
    assert side_out.exists()

    # Make one WAVES-style attacked folder without implementing any attack here.
    # In real experiments, this folder should be generated by the official WAVES
    # attack pipeline. For runability testing, copying is sufficient because
    # decode.py and metric.py only require the standard folder layout.
    synthetic_attacked = cv2.imread(str(wm_out), cv2.IMREAD_COLOR)
    # Change one pixel so PSNR is finite; this is only a folder-layout smoke test,
    # not an attack implementation.
    synthetic_attacked[0, 0, 0] = (int(synthetic_attacked[0, 0, 0]) + 1) % 256
    cv2.imwrite(str(attacked_wm_dir / "0.png"), synthetic_attacked)
    assert (attacked_wm_dir / "0.png").exists()

    # Official decode JSON output for clean real, clean watermarked, and attacked watermarked.
    decode_script.single_mode("arnold_hess", str(real_dir), quiet=True, subset=False, limit=1, subset_limit=1)
    decode_script.single_mode("arnold_hess", str(wm_dir), quiet=True, subset=False, limit=1, subset_limit=1)
    decode_script.single_mode("arnold_hess", str(attacked_wm_dir), quiet=True, subset=False, limit=1, subset_limit=1)

    clean_decode_json = result_dir / "custom" / "arnold_hess-decode.json"
    attacked_decode_json = result_dir / "custom" / "distortion_single_jpeg-0.5-arnold_hess-decode.json"
    assert clean_decode_json.exists()
    assert attacked_decode_json.exists()

    decoded = load_json(str(clean_decode_json))["0"]["arnold_hess"]
    msg = decode_array_from_string(decoded)
    assert msg.dtype == bool
    assert msg.shape == (16 * 16,)

    # Official lightweight metric JSON output.
    metric_script.single_mode("psnr", str(attacked_wm_dir), str(wm_dir), str(attacked_wm_dir), quiet=True, subset=False, limit=1, subset_limit=1)
    metric_script.single_mode("ssim", str(attacked_wm_dir), str(wm_dir), str(attacked_wm_dir), quiet=True, subset=False, limit=1, subset_limit=1)
    metric_script.single_mode("nmi", str(attacked_wm_dir), str(wm_dir), str(attacked_wm_dir), quiet=True, subset=False, limit=1, subset_limit=1)

    metric_json = result_dir / "custom" / "distortion_single_jpeg-0.5-arnold_hess-metric.json"
    assert metric_json.exists()
    metrics = load_json(str(metric_json))
    assert metrics["0"]["psnr"] is not None
    assert metrics["0"]["ssim"] is not None
    assert metrics["0"]["nmi"] is not None
